### ISSUE TITLE
Basic example of `pp_map` does not work

### ISSUE THREAD

**Issue by xapple** [uqfoundation/pathos#105]
This is what I typed to test the interesting "pp_map" function:

    xapple@server ~ $ ipython --banner
    Python 2.7.5 (default, Nov  6 2016, 00:28:07)
    Type "copyright", "credits" or "license" for more information.
    
    IPython 5.1.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    
    In [1]: import pathos
    
    In [2]: print pathos.__version__
    0.2.0
    
    In [3]: from pathos.pp_map import pp_map
    
    In [4]: print pp_map(lambda i: i * 2, [1, 2, 3, 4, 6, 7, 8])
    ---------------------------------------------------------------------------
    KeyError                                  Traceback (most recent call last)
    <ipython-input-4-968928b13682> in <module>()
    ----> 1 print pp_map(lambda i: i * 2, [1, 2, 3, 4, 6, 7, 8])
    
    /home/xapple/.local/lib/python2.7/site-packages/pathos/pp_map.pyc in pp_map(function, sequence, *args,     **kwds)
        168
        169 #   return Pool(procs, servers=servers).map(function, sequence, *args, **kwds)
    --> 170     if not __STATE['server']:
        171         __STATE['server'] = job_server = ppServer(ppservers=servers)
        172     return list(ppmap(procs,function,sequence,*args))
    
    KeyError: 'server'
    
    In [5]:

**Comment by xapple** [comment]
Until now I was using my own version of pp_map.

It is called `prll_map` and can be seen here: https://gist.github.com/xapple/77cc0c9e47f12d65953287faec27c0a9

It has a few nice features such as a progress bar, but isn't very robust when it comes to pickeling as you guessed.

**Comment by mmckerns** [comment]
@xapple: `pp_map` is deprecated, so I didn't notice that it hadn't moved along with recent updates.  Thanks for catching that.  I've made a patch to correct it, f46fa7a12964a7d517ef71ae14cc05e73df8a8b1.

The following test code should work for you, with the patch:
```
import pathos
print pathos.__version__
from pathos.pp_map import pp_map
f = lambda i: i*2
print pp_map(f, [1, 2, 3, 4, 6, 7, 8])
```

However, please note that the serialization of lambdas is a bit tricky, and even more so  when serializing by saving the source code (as is done by `ppft`, which is used by `pathos`).  The lambdas serialize by looking up the name reference (in this case, `f`) in the buffer memory... and thus, it can sometimes get it wrong if there are multiple reuses of `f` as a name reference in the recent buffer memory.  Note that the lambda is explicitly given a name reference `f` above, instead of declaring it inside the `pp_map` call.  This tends to yield better serialization results.

Note again that `pp_map` is a deprecated interface -- the preferred interface is identical to the `Pool` interface for `multiprocess`, as shown here:

```
>>> import pathos
>>> p = pathos.pools.ParallelPool()
>>> f = lambda i:i**2
>>> p.map(f, range(4))
[0, 1, 4, 9]
>>> p.close()
>>> p.clear()
>>> 
```

If you'd like to fold in some of the features of your own `prll_map`, please feel free to submit a PR.

**Comment by mmckerns** [comment]
If it still doesn't work for you, please re-open this ticket.

If you find bugs with `lambda` and maps derived from `ppft`, then please open a new ticket.  I know there are some bugs when it comes to locating the correct lambda 100% of the time from buffer memory.

**Comment by xapple** [comment]
OK cool, thanks a lot for the detailed answer, I will try it out!

**Comment by mmckerns** [comment]
for more details on my comments above, see issue #29
