### ISSUE TITLE
Advice on setting up a cluster?

### ISSUE THREAD

**Issue by honnibal** [uqfoundation/pathos#112]
Hi,

Thanks for making your tools available. I have a use-case that's very similar to mystic: I want to do hyper-parameter searches for ML models. As well as larger search jobs, I'd like to be able to submit individual training runs onto the same cluster.

My question is, how should I structure this? The simplest solution would be for my workstation to tunnel to the cluster and submit a `ParallelPool.map()` with the single task. However, I think this will assume the client will be connected for the lifetime of the job. This seems bad.

Instead I'm thinking I want something more like how Torque/SLURM are set up: I want to submit the job as a message, and have it complete asynchronously. I tried just using `amap`, but I'm getting a zero-division error if I set 0 local nodes (obviously I don't want my workstation in the cluster). I don't know whether this particular error is just a small bug I can fix, or whether using `amap` doesn't make sense here.

Thanks,
Matt

**Comment by mmckerns** [comment]
@honnibal: I'm not sure I understand what you are asking, can I get some clarification?  Here's what I think I'm hearing:
1) You want something like Torque/SLURM.
2) There may be a bug in pathos.pools.ParallelPool, for nodes=0.

So, to address (1): If you want to use Torque/SLURM, yes, you can do that.  There's `pyina`, which is another one of my packages.  It's due this year to be updated as python3 compatible and released... however the code from the git repository is stable.  There will be some changes before the release, but I don't think anything that breaks backward compatibility.  However, it's `pathos` that has `ssh-tunnel` capabilities, if you need that for connection purposes, so that's when you might have to mix `pyina` and `pathos` pools/pipes together.

For (2), I'm less clear what you are asking.  Can you provide a sample code to show the error you get, so I can try it?  I can build a `ParallelPool` with no local nodes.  It will hang, unless you have also registered a `ppft` server on your cluster.  If you do that, does `map` work, but `amap` doesn't?

**Comment by mmckerns** [comment]
Closing as stale.  This also may have been resolved by #189.  Reopen if needed.
