### ISSUE TITLE
after map I implement pool.close , raise error

### ISSUE THREAD

**Issue by Jxu-Thu** [uqfoundation/pathos#171]
from pathos.multiprocessing import ProcessingPool as Pool

pool = Pool(4)
 map_df = a python list
 pool_result = pool.map(my_func, map_df)
  v = pd.concat(pool_result, axis=0)
  
pool.close()
pool.join()

raise error : pool not running

**Comment by mmckerns** [comment]
@Jxu-Thu: You don't give me a lot of information to work with (i.e. version numbers of pathos, python, etc, full traceback, or even all of what you are doing).  However, I think I may know what your issue is regardless. So please reopen this ticket if I've not addressed your issue.

I believe you have probably called `pool.close()` somewhere earlier in your code.  Once you call `pool.close()`, the `pool` is no longer running.  Hence the error produced.

`pathos` unlike `multiprocessing` creates singleton pools... so by closing the pool, you close it for all `Pool(4)` instances.  To reopen the pool, you need to either need to use `pool.clear()` (and then generate a new `pool` instance) or use `pool.restart()` to reopen the pool.
