### ISSUE TITLE
Problem pickling lambda function

### ISSUE THREAD

**Issue by btlvr** [uqfoundation/pathos#196]
I have this code:
```python
from pathos.multiprocessing import ProcessingPool

items = [1,2,3]

def expand(func):
	expected_result = map(func, items)
	pathos_result = ProcessingPool().map(func, items)

	return list(pathos_result), list(expected_result)

for power in [3,2,1]:
	print(expand(lambda x : x**power))
```

Which outputs:
```python
([1, 8, 27], [1, 8, 27])
([1, 8, 27], [1, 4, 9])
([1, 8, 27], [1, 2, 3])
```

Why doesn't it produce the following output?
```python
([1, 8, 27], [1, 8, 27])
([1, 4, 9], [1, 4, 9])
([1, 2, 3], [1, 2, 3])
```

I've tried pathos 0.2.3 and 0.2.6

**Comment by emorice** [comment]
I think what you want is:

```python
from pathos.multiprocessing import ProcessingPool

items = [1,2,3]

def expand(func):
	expected_result = map(func, items)
	pathos_result = ProcessingPool().map(func, items)

	return list(pathos_result), list(expected_result)

for power in [3,2,1]:
	print(expand(lambda x, power=power: x**power))
```

Which works as expected for me:
```
([1, 8, 27], [1, 8, 27])
([1, 4, 9], [1, 4, 9])
([1, 2, 3], [1, 2, 3])
```

This is a classical pattern when dealing with closures in python, compare:
```py
>>> funcs = [(lambda : x) for x in [1, 2, 3]]
>>> [f() for f in funcs]
```
```
[3, 3, 3]
```

and:

```py
>>> funcs = [(lambda value=x: value) for x in [1, 2, 3]]
>>> [f() for f in funcs]
```
```
[1, 2, 3]
```

And see [the python FAQ](https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result) for the detailed explanation.

In short, your lambdas all refers to the same shared variable from the enclosing scope instead of having their own copy, which behaves as expected when you evaluate them right away in the same environment but break downs when you need to do more exotic things with them such as sending them to other workers.

**Comment by mmckerns** [comment]
Thanks @emorice for the nice response.  @btlvr if this answers your question, please close the ticket.
