### ISSUE TITLE
Avoid repeating serialization of same objects 

### ISSUE THREAD

**Issue by mattiasmar** [uqfoundation/pathos#249]
Hello,
In every subprocess of `map`  I am accessing the same object instances (which are expensive to serialize ). Without assorting to globals how can I have pathos do parallel processing (using map), while avoiding repeating serialization of my large object instances over and over again?

```
class TestParallelization:
    def __init__():
         self.pool = pathos.multiprocessing.ProcessPool(25)
         self.very_large_object = large_obj()
    
    def foo(self, parameter):
          result =  some_function( self.very_large_object, parameter)
          return result

    def parallelized_execution1():
          # This line would cause "self" to be serialized 50 times (including the  self.very_large_object)
          results1 = self.pool.map(self.foo, [list(range(50)])  
    
    def foo2(a_large_object, parameter):
          result =  some_function( a_large_object, parameter)
          return result

    def parallelized_execution2():
          # This line would also cause the very_large_object  to be serialized 50 times
          foo3 =  partial(TestParallelization.foo2, self.very_large_object)
          results1 = self.pool.map(foo3, [list(range(50)])  
```

**Comment by mmckerns** [comment]
You could try working in thread-parallel, so instead of `pathos.pools.ProcessPool`, use `pathos.pools.ThreadPool`.  Thread-parallel can share the objects without the need to serialize them.  If you want to use process-parallel computing, then you'll either need to serialize the objects to transfer them across processes... or convert the objects to source code (with `pathos.pools.ParallelPool`)... or you can use `multiprocess` shared objects (see `multiprocess.Manager`).

Please reopen if this doesn't sufficiently answer your question.
