### ISSUE TITLE
howto in pathos/external/readme.txt not correct ?

### ISSUE THREAD

**Issue by moritz-imendoerffer** [uqfoundation/pathos#47]
Tried to install pathos. I followed the instructions according to the readme file in pathon/external with two exception:
To install the external packages:

I  had to use  pp-1.6.4.4.zip, otherwise the pathos installation tried to download 1.6.4.4 and failed  with an error: ImportError: cannot import name __version__

    $ unzip pp-1.6.4.2.zip
    $ cd ../pp-1.6.4.2
    $ python setup.py build
    $ python setup.py install

The setup.py file was not in the folder pathos/external/pyre but in the folder pathos/external
    $ cd ../pyre-0.8-pathos
    $ python setup.py build
    $ python setup.py install

After these changes the installation of pathos seemed to work.

**Comment by mmckerns** [comment]
The README and `setup.py` should be fixed in: 0d2be2b42d9be603e44c800c6ab987e72986921a and 601dcd6ddf233a120e2f722262c84f8005596bc4.  Before I close this, can you let me know exactly what your error was (e.g. can you clip and post it, if you still have it in your shell)?  I want to make sure I have your issue covered.  I'm didn't see an error when I tried my own install just now.

**Comment by mmckerns** [comment]
BTW: the version of `pyre` to install should be `0.8.2-pathos`, not `0.8-pathos`.  I clarified the `README` -- it was noted at the bottom, for some reason, and not directly in the install instructions.

I'm in the process of cleaning the package dependencies up so `pathos` can just pip install, hopefully soon.

**Comment by moritz-imendoerffer** [comment]
unfortunately i do not have the error message anymore.

THX for this great package
