### ISSUE TITLE
WindowsError when trying to use pathos.multiprocessing

### ISSUE THREAD

**Issue by jjw2154** [uqfoundation/pathos#60]
I have installed `pathos` on my computer (Windows 7 64-bit) but keep getting a `WindowsError` whenever I try to use it. . I'm using pathos version 0.2a1.dev0 and Dill version 0.2.2. This error seems to be reproducible when ever I create a `Pool`. 

Details here: http://stackoverflow.com/questions/29887878/windowserror-in-pathos-multiprocessing/29887981#29887981

**Comment by mmckerns** [comment]
@jjw2154: As noted in the answer to your stack-overflow question, it seems like this is a bug in the `processing` library, which may actually be a underlying `python` bug.  See the details in ticket #49.

If the standard `multiprocessing` does not have this issue for you (in `python` 2.7, I assume), then as a resolution, I can probably grab the patch from that library… as I believe the `python` bug still is is unresolved.

I closed #49, due to it being a `python` bug, and not being able to directly work at the installation issue.  However, if this is the same issue (or at least strongly related) and you do have a `multiprocessing` version that works… I'll leave this open, to be patched.

Can you give your python version, and compiler information?

**Comment by mmckerns** [comment]
From comments in the SO link above:
> I re-installed pathos and still got the same error when I use pathos.multirpocessing.Core. But if I use pathos.pp.ParallelProcessingPool, the example code (from the pathos site) works. I was unable to use it for my code though; it seems the dill was also unable to pickle a portion of the code. At this point, though, it may be simpler to run my program on a single core. Anyway, thanks for the prompt responses. –  wye_naught Apr 30 at 0:24

First off, there is no `pathos.multiprocessing.Core`, maybe you mean `pathos.core`?  Regardless, please feel free to share what bugs or missing features you found.  That's the only way they can be patched/added.  You can open a new ticket if you'd like to report.  I'm marking this as duplicate, as that's what it seems to be, from what you've reported.

**Comment by jjw2154** [comment]
Just for the record (from StackOverflow):

>Sorry...I meant to type pathos.multiprocessing.Pool. It's probably the same ticket on github as you have mentioned above

**Comment by mmckerns** [comment]
Ok, thanks.

**Comment by mmckerns** [comment]
Note as tracked in #2, the install just got a bit easier, more stable, and more robust… but still needs a little work.
