### ISSUE TITLE
some modules fail to serialize with pathos.pp

### ISSUE THREAD

**Issue by VanyaBelyaev** [uqfoundation/pathos#78]
I am using pathos for my project and it works nicely for multiprocessing. However for parallel python I've got a problem - the system hangs on job submission.  With some investigation I've found an easy way to reproduce the problem using standard example sum_primesX.py.   It is enough  to add 'readline' module into the list of modules to be imported and system hangs at submission:

replace :

```
jobs = [(input, job_server.submit(sum_primes, (input, ), (isprime, ),
        ("math", ))) for input in inputs]
```

with

```
 jobs = [(input, job_server.submit(sum_primes, (input, ), (isprime, ),
        ("math", "readline")) for input in inputs]
```

Is it a known issue?  Is there any solution?

**Comment by mmckerns** [comment]
Can you clarify what you mean by "`pathos` has a problem" and "for parallel python, I've got a problem"?  Are you talking about using raw `pp` (parallel python) or `ppft` (my augmented fork of `pp`), or `pathos.pp` (which uses `ppft`)? 

If you are using `job_server.submit`, you probably aren't using `pathos`, technically… and indeed `sum_primesX.py` doesn't use `ppft` or `pathos`… it uses `pp`.  `pp` has issues with parallelizing a lot of objects because it will fail whenever it can't get the source code of something… modules included -- the fork `ppft` uses `dill.source` to do a better job of extracting the source of any object.

So, given that information, can you refine what you are asking?

**Comment by VanyaBelyaev** [comment]
I've installed whole pathos suite from git-master (including dill, pptf, ...) and  I've cross-checked that 
import pp" actually imports pptf and dill. [For simplicity I've added some prints into ppworker.py form pptf]   

When I use this  construction (with pptf+dill) for my project, it hangs on submission, unless the function to be  executed is really trivial. Gradually making the function simpler and simple I've observed that problem  can be reproduced with very simple setup described above.

Since the problem is easy to reproduce, I'd like to know if it is a feature of pptf? should I make a try with native pathos methods?

**Comment by VanyaBelyaev** [comment]
I've tried to play with  test_ppmap2.py example.
It works nicely, but if I'add the line "import readline" into host function, it hangs:

```
def host(id):
    import socket
    import readline  ## adding this line causes problems 
    import time
    time.sleep(1.0)
    return "Rank: %d -- %s" % (id, socket.gethostname())

```

**Comment by mmckerns** [comment]
There shouldn't be an issue with modules like `readline`.  I'm going to guess that whatever it is, it's because `readline` is included in python as a shared object (.so).  `pp` and thus `ppft` extracts the source of the object and then rebuilds on the other resource -- instead of serializing to byte code.  However, `ppft` uses `dill.source.importable`, which for modules either gets the full source or an short string with an import (e.g. "`import readline\n`").  You can see this behavior below:

```
>>> import dill
>>> import readline
>>> 
>>> dill.dumps(readline)
'\x80\x02cdill.dill\n_import_module\nq\x00U\x08readlineq\x01\x85q\x02Rq\x03.'
>>> dill.copy(readline)
<module 'readline' from '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/readline/readline.so'>
>>> dill.check(readline)
<module 'readline' from '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/readline/readline.so'>
>>> dill.source.importable(readline)
'import readline\n'
>>>
```
So, in the above, `copy` is a `dumps` and `loads` where object sharing is allowed (like done in `multiprocess` on linux), and `check` is a `copy` where object sharing is not allowed (as done on windows or in `ppft`).  You can see it handles `readline` just fine.

So, here's a function with `readline` in it: 
```
>>> def doit(x):
...   import readline
...   return x
… 
>>>
>>> dill.dumps(doit)
'\x80\x02cdill.dill\n_create_function\nq\x00(cdill.dill\n_load_type\nq\x01U\x08CodeTypeq\x02\x85q\x03Rq\x04(K\x01K\x02K\x02KCU\x10d\x01\x00d\x00\x00l\x00\x00}\x01\x00|\x00\x00Sq\x05NJ\xff\xff\xff\xff\x86q\x06U\x08readlineq\x07\x85q\x08U\x01xq\th\x07\x86q\nU\x07<stdin>q\x0bU\x04doitq\x0cK\x01U\x04\x00\x01\x0c\x01q\r))tq\x0eRq\x0fc__builtin__\n__main__\nh\x0cNN}q\x10tq\x11Rq\x12.'
>>> dill.copy(doit)
<function doit at 0x107c3ba28>
>>> dill.check(doit)
<function doit at 0x10c2da2a8>
>>> dill.source.importable(doit)
'def doit(x):\n  import readline\n  return x\n'
>>> 
```
Again, this works.

So now, in `ppft` (via `pathos`)…  you can see there's some issues…
```
>>> import pathos
>>> pool = pathos.pools.ParallelPool(2)
>>> pool
<pool ParallelPool(ncpus=2, servers=None)>
>>> res = pool.imap(doit, range(2))
>>> Python(691,0x108629000) malloc: *** mmap(size=1971238742399336448) failed (error code=12)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Python(691,0x108a2c000) malloc: *** mmap(size=1971238742399336448) failed (error code=12)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
```

Is this something like what you are seeing?  (it also hangs for `map` instead of `imap` above)

If so, I might understand what's causing it, but am not sure how to fix it just yet.  `map` has to allocate the correct-sized memory for the object that is being passed, and if it were to poorly estimate the size of the object, it might throw a `malloc_error`… and I'm wondering if that's happening due to the use of "`import readline\n`" as opposed to the actual size of the module object itself in python.  I'm not sure… but it seems to be a bug.

Any more information you can provide would be helpful… especially if you are seeing a different traceback than the above.

**Comment by mmckerns** [comment]
I'm not sure if this is a `pathos` issue, however, it might actually be a `ppft` issue as you are seeing errors with `job_server`.   Can you post a full reduced example (as above) using `ppft` directly with a `job_server`… and include the traceback, if there's also an error?

**Comment by mmckerns** [comment]
Upon further testing, this no longer seems to be an issue.  Closing.
