### ISSUE TITLE
Issue installing/importing pathos.multiprocessing? `ImportError: No module named multiprocessing`

### ISSUE THREAD

**Issue by emunsing** [uqfoundation/pathos#89]
I'm interested in using pathos for research, and have tried installing it using the directions at https://pypi.python.org/pypi/pathos (using both easy_install and through building/installing from the tarball) as well as through `$ pip install git+github.com/uqfoundation/pathos`. For all of these, when I try running `from pathos.multiprocessing import ProcessingPool` in my python 2.7 interpreter  I get `ImportError: No module named multiprocessing`

How should I be installing this to be able to use your Multiprocessing functionality? If you're able to update the documentation to clarify this, it would also help others with the same question!

Looking forwards to using it; it sounds like a very useful tool.

**Comment by mmckerns** [comment]
I will have a standard `pip` install in a few days, as there's an imminent release due (in a day or two).   However, currently, any of the methods detailed in #2 should work.  I don't know why you aren't seeing `pathos.multiprocessing`. I'd need a bit more information.  What's you OS, and do you have a C/C++ compiler?  (To install `multiprocess` correctly, you need a C++ compiler).  You can check you install of `multiprocess` by trying `import multiprocess` (python module) and `import _multiprocess` (C++ module).

**Comment by mmckerns** [comment]
@emunsing: I'm wondering if you first used `easy_install`, which may have installed a really old version of `pathos` (i.e. one from 5+ years ago where  `pathos.multiprocesssing` may have either been named otherwise or wasn't included in the `__init__` imports).  Then, when you later installed with `pip`, it may not have done a full install (i.e. it saw dependencies have been satisfied, and you didn't force the update).  If this is the case, you might want to `uninstall` and then `install` again, or to force an update.

**Comment by emunsing** [comment]
Thanks, Mike- You're correct that I first used easy_install, which must have interefered with the full install from github.  Uninstalling everything and then reinstalling with `pip install git+https://github.com/uqfoundation/pathos` worked great.  Thanks a ton for the fast response and the incredible amount of work you've put into this; I look forwards to using it and seeing it as a pip package!
